### ISSUE TITLE
Dragging selects text on every second drag on Safari

### ISSUE THREAD

**Issue by hphaavikko** [SortableJS/vue.draggable.next#16]
Dragging selects text on every second drag on Safari. Same issue is reported on older vue Draggable versions as well https://github.com/SortableJS/Vue.Draggable/issues/743 but the mentioned forceFallback option didn't work.

You can reproduce the issue by trying the live demo with Safari: https://sortablejs.github.io/vue.draggable.next/#/simple Drag once and it works, drag a second time and it selects text. Drag third time and it works, fourth time it selects text and so on.

It tried setting user-select: none to the item css (with all prefixes as well) but it doesn't help; then Safari just starts selecting text from the first selectable element before the draggable list.

**Comment by ctessmer** [comment]
**This problem happens on iOS Safari too.**

Every second tap and drag selects text—just like @hphaavikko described—instead of dragging the item. Tested (and failed) on:

- macOS 10.15.7; Safari 14.0.1
- iOS 14.4; Safari 14

I tested it on Firefox Developer Edition 87.0b5. It works like a charm. 

Awesome library. **Really hope Apple users get some love here.** I mean, iPhones 📱 seem to be *somewhat* popular… 😉

**Comment by ahoiroman** [comment]
Seems like `forceFallback` didn't make it to `vuedraggable@next`. Would love to see this as I can't migrate to Vue3 with this behavior on Safari.

**Comment by apodacaduron** [comment]
This was fixed in SortableJS https://github.com/SortableJS/Sortable/releases/tag/1.13.0, but I have no idea why they haven't updated the package yet, this library still in v1.10 of SortableJS 😭

**Comment by HanKruiger** [comment]
It looks like this can be closed now, as `vue.draggable.next` uses SortableJS 1.14 and I can no longer reproduce the issue.

**Comment by SionGrey** [comment]
No, it is can not be closed - version 4.1.0 of oackage and on iOS 18.5 still mess

**Comment by lukeupup** [comment]
If you use vue.draggable.next and still have the same problem, it might because the browser type check fails in Sortable.js. Try to set the `supportPointer` to `false` on your component (although it's not documented in anywhere):

```
<VueDraggable
  ...
  :supportPointer="false"
></VueDraggable>
```
